version: "3.9"
services:
    api:
        container_name: api
        build:
            context: .
            target: php
        environment:
            - PORT=8080
            - APP_ENV=${APP_ENV}
            - PHP_OPCACHE_ENABLE=1
            - PHP_OPCACHE_ENABLE_CLI=0
            - PHP_OPCACHE_REVALIDATE_FREQ=1
            - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - "80:8080"
        depends_on:
            - database
            - database-testing
    database:
        container_name: database
        image: mysql:8.0
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        volumes:
            - "db-data:/var/lib/mysql"
    database-testing:
        container_name: database-testing
        image: mysql:8.0
        ports:
            - "3008:3306"
        environment:
            - MYSQL_DATABASE=${DB_DATABASE_TESTING}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        volumes:
            - "db-testing-data:/var/lib/mysql"
volumes:
    db-data:
        name: db-data
    db-testing-data:
        name: db-testing-data
